[package]
name = "wasmedge_rustls_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio_wasi = { version = "1", optional = true }

[features]
default = []
tokio_async = ["tokio_wasi"]
